package uz.barakat.market.domain;

/** Types of immutable, server-calculated SavdoGraph evidence. */
public enum EvidenceType {
    REORDER_QUANTITY,
    PERIOD_TIMEZONE,
    REVENUE,
    REFUNDED_REVENUE,
    COGS,
    GROSS_PROFIT,
    GROSS_MARGIN,
    SOURCE_RECORD_COUNT,
    RESULT_CLASSIFICATION,
    REORDER_CURRENT_STOCK,
    REORDER_NET_UNITS_SOLD,
    REORDER_VELOCITY,
    REORDER_COVERAGE_BEFORE,
    REORDER_COVERAGE_AFTER,
    REORDER_STOCKOUT_RISK,
    REORDER_OVERSTOCK_RISK,
    REORDER_TIED_UP_CAPITAL
}
