-- SavdoGraph B1: evidence-backed, tenant-scoped human-approval foundation.
-- Every business record is scoped by shop_id. The application also applies the
-- existing Hibernate tenant filters and TenantScopedEntity post-load guard.

CREATE TABLE savdograph_analysis_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL REFERENCES shops(id),
    analysis_type VARCHAR(64) NOT NULL,
    period_from DATE NOT NULL,
    period_to DATE NOT NULL,
    status VARCHAR(32) NOT NULL,
    initiated_by VARCHAR(80) NOT NULL,
    tool_version VARCHAR(80) NOT NULL,
    input_snapshot TEXT NOT NULL,
    input_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_sg_analysis_run_shop_created
    ON savdograph_analysis_run (shop_id, created_at DESC);

CREATE TABLE savdograph_evidence_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL REFERENCES shops(id),
    analysis_run_id BIGINT NOT NULL REFERENCES savdograph_analysis_run(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    evidence_type VARCHAR(64) NOT NULL,
    source_type VARCHAR(64) NOT NULL,
    period_from DATE NOT NULL,
    period_to DATE NOT NULL,
    calculation_id VARCHAR(96) NOT NULL,
    calculation_version VARCHAR(80) NOT NULL,
    input_data TEXT NOT NULL,
    calculated_result DECIMAL(19,4),
    unit VARCHAR(24),
    currency VARCHAR(3),
    content_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_sg_evidence_content UNIQUE (shop_id, analysis_run_id, content_hash)
);

CREATE INDEX idx_sg_evidence_shop_run
    ON savdograph_evidence_item (shop_id, analysis_run_id, id DESC);

CREATE TABLE savdograph_decision_proposal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL REFERENCES shops(id),
    analysis_run_id BIGINT NOT NULL REFERENCES savdograph_analysis_run(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    supplier_id BIGINT NOT NULL REFERENCES suppliers(id),
    proposal_type VARCHAR(32) NOT NULL,
    proposed_reorder_quantity INTEGER NOT NULL,
    expected_impact TEXT NOT NULL,
    risk_summary TEXT NOT NULL,
    assumptions TEXT NOT NULL,
    status VARCHAR(32) NOT NULL,
    evidence_hash VARCHAR(64) NOT NULL,
    created_by VARCHAR(80) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_sg_proposal_shop_created
    ON savdograph_decision_proposal (shop_id, created_at DESC);

CREATE TABLE savdograph_proposal_evidence (
    proposal_id BIGINT NOT NULL REFERENCES savdograph_decision_proposal(id) ON DELETE CASCADE,
    evidence_id BIGINT NOT NULL REFERENCES savdograph_evidence_item(id),
    PRIMARY KEY (proposal_id, evidence_id)
);

CREATE TABLE savdograph_proposal_decision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL REFERENCES shops(id),
    proposal_id BIGINT NOT NULL REFERENCES savdograph_decision_proposal(id),
    decision VARCHAR(16) NOT NULL,
    actor VARCHAR(80) NOT NULL,
    reason VARCHAR(500),
    idempotency_key VARCHAR(120) NOT NULL,
    purchase_order_id BIGINT REFERENCES purchase_order(id),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_sg_proposal_decision UNIQUE (proposal_id),
    CONSTRAINT uq_sg_decision_idempotency UNIQUE (proposal_id, idempotency_key)
);

CREATE INDEX idx_sg_decision_shop_proposal
    ON savdograph_proposal_decision (shop_id, proposal_id);

CREATE TABLE savdograph_action_ledger_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL REFERENCES shops(id),
    proposal_id BIGINT REFERENCES savdograph_decision_proposal(id),
    proposal_decision_id BIGINT REFERENCES savdograph_proposal_decision(id),
    actor VARCHAR(80) NOT NULL,
    evidence_references TEXT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    outcome VARCHAR(64) NOT NULL,
    purchase_order_id BIGINT REFERENCES purchase_order(id),
    details VARCHAR(500),
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_sg_ledger_shop_created
    ON savdograph_action_ledger_event (shop_id, created_at DESC);
CREATE INDEX idx_sg_ledger_proposal
    ON savdograph_action_ledger_event (proposal_id, id DESC);
